tasks:
  - init: pip install . && python -c "import nltk; nltk.download('punkt')" && pip install -U numpy
  - command: sumy lex-rank --length=10 --url=http://en.wikipedia.org/wiki/Automatic_summarization
